[browser]
gatherUsageStats = false

[server]
fileWatcherType = "none"
headless = true
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#e53935"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#17324f"
